"use strict";
exports.__esModule = true;
var caminhao_1 = require("./caminhao");
var onibus_1 = require("./onibus");
console.log("Criação da instancia de Onibus");
var onibus = new onibus_1["default"]("ABC1234", 2020, 50);
onibus.exibirDados();
var numAssentosOriginal = onibus.getAssentos();
onibus.setAssentos(45);
var numAssentosAlterado = onibus.getAssentos();
console.log("Houve uma altera\u00E7\u00E3o de ".concat(numAssentosOriginal, " para ").concat(numAssentosAlterado, " na quantidade de assentos instalados no onibus"));
console.log("Configuração final do onibus:");
onibus.exibirDados();
console.log("-------------");
console.log("Criação da instancia de Caminhão");
var caminhao = new caminhao_1["default"]("ABC1234", 2022, 2);
caminhao.exibirDados();
var novaPlaca = "DEF1234";
console.log("A placa ".concat(caminhao.getPlaca(), " ja esta em uso e sera alterada para ").concat(novaPlaca));
caminhao.setPlaca(novaPlaca);
console.log("Configuração final do caminhão:");
caminhao.exibirDados();
